#!/usr/bin/env python3

import sys
from math import *

class matrix :
    def _init_(self, x, y):
        self.x = x
        self.y = y
        return matrix(x, y)

def print_matrix(args):
    try:
        x = int(args[0])
        y = int(args[1])

        print(f"{x}")
        print(f"{y}")
        print("1")
    except ValueError :
        sys.exit(84)

def main(args):
    print_matrix(args)
    sys.exit(0)

if __name__ == "__main__" and len(sys.argv[1:]) == 2:
    main(sys.argv[1:])
else:
    sys.exit(84)